apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: cs21-peer-mentor-client
          image: thetkpark/cs21-peer-mentor-client:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: https://2b1235c80c26.ap.ngrok.io/api
            - name: NEXT_PUBLIC_SOCKET_URL
              value: https://2b1235c80c26.ap.ngrok.io/socket
