apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: cs21-peer-mentor-client
          image: thetkpark/cs21-peer-mentor-client
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: SERVER_URL
            - name: NEXT_PUBLIC_SOCKET_URL
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: SOCKET_URL
