apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: cs21-peer-mentor-client
          image: cs21-peer-mentor-client
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: http://localhost/api
            - name: NEXT_PUBLIC_SOCKET_URL
              value: http://localhost/socket