apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/websocket-services : socket-cluster-ip-service
    # nginx.org/websocket-services: socket-cluster-ip-service
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  tls:
    - hosts:
      - cs21.cscms.me
      secretName: cs21-cf
    - hosts:
      - cs21socket.cscms.me
      secretName: cs21-socket-cf
  rules:
    - host: cs21socket.cscms.me
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: socket-cluster-ip-service
              servicePort: 5000
    - host: cs21.cscms.me
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 3050
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
