apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      volumes:
        - name: gcs-service-account-json
          secret:
            secretName: gcs-service-account
      containers:
        - name: cs21-peer-mentor-server
          image: thetkpark/cs21-peer-mentor-server
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: gcs-service-account-json
              mountPath: /etc/gcs
              readOnly: true
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "300m"
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: MONGO_CONNECTION_STRING
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: CLIENT_URL
            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: SERVER_URL
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: SESSION_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: REDIS_PASSWORD
            - name: MSAPP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: MSAPP_CLIENT_ID
            - name: MSAPP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: MSAPP_CLIENT_SECRET
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: GCS_BUCKET_NAME
            - name: GCS_KEY_PATH
              value: /etc/gcs/gcs
            - name: GCS_BUCKET_PATH
              valueFrom:
                configMapKeyRef:
                  name: components-config
                  key: GCS_BUCKET_PATH
            - name: COSMODDB_USER
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: COSMODDB_USER
            - name: COSMOSDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: COSMOSDB_PASSWORD
            - name: COSMOSDB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: COSMOSDB_DBNAME
            - name: COSMOSDB_HOST
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: COSMOSDB_HOST
            - name: COSMOSDB_PORT
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: COSMOSDB_PORT